Repository SPACEMAP-WEB/spacemap-platform-api, pull requests merged in 2022-07, with the labels that each got.

#39 Feat/mailing : new features
  .gitignore
  package-lock.json
  package.json
  src/api/interestedSatellites/interestedSatellites.service.js
  src/api/interestedSatellites/interestedSatellites.task.js
  src/lib/html-handler.js
  src/lib/interestedSatellites-handler.js
  src/lib/node-mailer.js
Labels: enhancement

#46 Fix: favorite conjunctions (filter)
  src/api/interestedSatellites/interestedSatellites.controller.js
Labels: bug

#59 Refactor/trajectory
  src/api/launchConjunctions/launchConjunctions.controller.js
  src/api/launchConjunctions/launchConjunctions.metaData.js
  src/api/launchConjunctions/launchConjunctions.s3handler.js
  src/api/launchConjunctions/launchConjunctions.secondAndPosition.js
  src/api/launchConjunctions/launchConjunctions.service.js
  src/api/launchConjunctions/launchConjunctions.trajectory.js
  src/api/watcherCatchers/watcherCatchers.controller.js
  src/lib/date-handler.js
  src/lib/launchConjunction-handler.js
  src/lib/s3-handler.js
  src/lib/trajectory-handler.js
Labels: enhancement

#69 Feat/cola
  ecosystem.config.js
  src/api/collisionAvoidance/coladb.model.js
  src/api/collisionAvoidance/coladb.service.js
  src/api/collisionAvoidance/collisionAvoidance.controller.js
  src/api/collisionAvoidance/collisionAvoidance.model.js
  src/api/collisionAvoidance/collisionAvoidance.service.js
  src/api/watcherCatcher/watcherCatcher.controller.js
  src/api/watcherCatcher/watcherCatcher.lib.js
  src/api/watcherCatcher/watcherCatcher.model.js
  src/api/watcherCatcher/watcherCatcher.service.js
  src/api/watcherCatcher/watcherCatcher.task.js
  src/lib/engine-command.js
  src/server.js
Labels: refactor
