Repository SPACEMAP-WEB/spacemap-platform-api, pull requests merged in 2022-08, with the labels that each got.

#70 Feat/cola
  src/api/collisionAvoidance/collisionAvoidance.controller.js
  src/api/collisionAvoidance/collisionAvoidance.lib.js
  src/api/collisionAvoidance/collisionAvoidance.model.js
  src/api/collisionAvoidance/collisionAvoidance.service.js
  src/api/ppdbs/ppdb.controller.js
  src/server.js
Labels: enhancement

#72 Refactor/tasks: remove unused tasks
  src/api/collisionAvoidance/coladb.service.js
  src/api/collisionAvoidance/collisionAvoidance.service.js
  src/api/launchConjunctions/launchConjunctions.lib.js
  src/api/launchConjunctions/launchConjunctions.service.js
  src/api/launchConjunctions/launchConjunctions.task.js
  src/api/launchConjunctions/lpdb.model.js
  src/api/lpdb/lpdb.service.js
  src/api/ppdbs/eventseq.task.js
  src/api/ppdbs/ppdb.lib.js
  src/api/ppdbs/ppdb.service.js
  src/api/ppdbs/ppdb.task.js
  src/api/rso/rso.lib.js
  src/api/rso/rso.service.js
  src/api/rso/rso.task.js
  src/api/tasks/task.controller.js
  src/api/tles/tle.lib.js
  src/api/tles/tle.service.js
  src/api/tles/tle.task.js
  src/api/watcherCatcher/watcherCatcher.lib.js
  src/api/watcherCatcher/watcherCatcher.service.js
  src/api/watcherCatcher/watcherCatcher.task.js
  src/api/watcherCatcher/wcdb.model.js
  src/api/wcdb/wcdb.service.js
  src/server.js
  unused/sftp-handler.js
  unused/ssh-handler.js
Labels: refactor

#73 Fix: calculate only between pw
  src/api/collisionAvoidance/collisionAvoidance.controller.js
  src/api/launchConjunctions/launchConjunctions.controller.js
  src/api/launchConjunctions/launchConjunctions.trajectory.js
  src/api/watcherCatcher/watcherCatcher.controller.js
  src/lib/date-handler.js
Labels: refactor

#77 Feat/log
  .prettierrc
  src/api/interestedSatellites/interestedSatellites.task.js
  src/api/log/log.controller.js
  src/api/log/log.model.js
  src/api/log/log.service.js
  src/api/log/log.task.js
  src/api/tasks/task.controller.js
  src/api/templates/template.controller.js
  src/lib/node-mailer.js
  src/server.js
  src/templates/logReport.ejs
Labels: enhancement

#78 Develop
  .prettierrc
  src/api/interestedSatellites/interestedSatellites.task.js
  src/api/log/log.controller.js
  src/api/log/log.model.js
  src/api/log/log.service.js
  src/api/log/log.task.js
  src/api/tasks/task.controller.js
  src/api/templates/template.controller.js
  src/api/watcherCatcher/watcherCatcher.controller.js
  src/lib/node-mailer.js
  src/server.js
  src/templates/logReport.ejs
Labels: enhancement

#79 Develop
  src/api/collisionAvoidance/collisionAvoidance.controller.js
  src/api/launchConjunctions/launchConjunctions.controller.js
  src/api/watcherCatcher/watcherCatcher.controller.js
  src/lib/date-handler.js
  src/templates/test.html
Labels: refactor

#83 Fix: ser
  src/api/interestedSatellites/interestedSatellites.task.js
  src/templates/spaceEventReport.ejs
  src/templates/static/common.css
Labels: refactor

#85 Develop
  ecosystem.config.js
  src/api/collisionAvoidance/collisionAvoidance.controller.js
  src/api/interestedSatellites/interestedSatellites.controller.js
  src/api/interestedSatellites/interestedSatellites.service.js
  src/api/launchConjunctions/launchConjunctions.controller.js
  src/api/launchConjunctions/launchConjunctions.service.js
  src/api/launchConjunctions/launchConjunctions.trajectory.js
  src/api/watcherCatcher/watcherCatcher.controller.js
  src/lib/date-handler.js
Labels: bug
